# config.py

HOST = '10.30.202.139'
PORT = 4001
LEASE_TIME = 10
REQUEST_IP = "REQUEST_IP"
UPDATE_LEASE = "UPDATE_LEASE"
ASSIGNED_IP = "ASSIGNED_IP"
LEASE_UPDATED = "LEASE_UPDATED"
NO_IP_ASSIGNED = "NO_IP_ASSIGNED"
